---
- name: Install HAProxy
  ansible.builtin.dnf:
    name:
      - haproxy
      - policycoreutils-python-utils
    state: present

- name: Allow HAProxy to bind to network ports
  ansible.posix.seboolean:
    name: haproxy_connect_any
    state: true
    persistent: true

- name: Deploy HAProxy configuration
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: "0644"
    validate: "haproxy -c -f %s"
  notify: Restart HAProxy

- name: Enable HAProxy
  ansible.builtin.systemd:
    name: haproxy
    enabled: true
    state: started
