---
- name: Validate Cinder CSI prerequisites and create Namespace
  ansible.builtin.include_tasks:
    file: validate.yml

- name: Configure Cinder CSI credentials
  ansible.builtin.include_tasks:
    file: secret.yml

- name: Install Cinder CSI
  ansible.builtin.include_tasks:
    file: install.yml

- name: Configure Cinder CSI StorageClasses
  ansible.builtin.include_tasks:
    file: storageclasses.yml
