---
- name: Create or update Cinder CSI OpenStack credentials Secret
  kubernetes.core.k8s:
    kubeconfig: "{{ cinder_csi_kubeconfig }}"
    api_version: v1
    kind: Secret
    namespace: "{{ cinder_csi_namespace }}"
    name: "{{ cinder_csi_secret_name }}"
    state: present
    definition:
      metadata:
        labels:
          app.kubernetes.io/name: openstack-cinder-csi
          app.kubernetes.io/component: credentials
      type: Opaque
      stringData:
        "{{ cinder_csi_secret_filename }}": |-
          [Global]
          auth-url = {{ cinder_csi_auth_url }}
          application-credential-id = {{ cinder_csi_application_credential_id }}
          application-credential-secret = {{ cinder_csi_application_credential_secret }}
          region = {{ cinder_csi_region }}
          tenant-id = {{ cinder_csi_project_id }}
          auth-type = v3applicationcredential

          [BlockStorage]
          ignore-volume-az = true
  no_log: true
