---
- name: Install base packages
  ansible.builtin.dnf:
    name:
      - curl
      - wget
      - git
      - vim-enhanced
      - jq
      - rsync
      - chrony
      - tar
      - unzip
      - bash-completion
    state: present

- name: Enable chronyd
  ansible.builtin.systemd:
    name: chronyd
    enabled: true
    state: started
