---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: acp-signing
  namespace: quantum-platform
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    private.pem: AgCm/3qEXa/UxVEuQdH3tAGzGXRXLSJBbQmpChAF0rftW2bDNKjZ108AmCdqJZoNaZrrpZWG7iXv8zqZXzguatIF782OcOWeygx8eHwlYvqZHNkU92dOeYxDZ0PsqH7TKdkEMsOh+3xNc4WEXfnf0dHrkuCbycggkhQJGU0vAvE2JdW5Ei0FK+DH/ZFCuvuAwtOw8VwhF9XO67FvspehhU3uQgWyZrR/NxZyQFUVbfctiGYqIPCyKVIRHaynZ9VDzPSOCOKHyGD+urfNaV9obWTEjVSKOmKeXX8dJnkTmU8rZkNrkBsQVx1OJt1pn5WwJzIdbsrxWHkiPpUDTlGyLtaAJ/Vq7EZbMH/yCzYmLeETDJWpOacHRjWbLVpyoSXdcgvgcN/FNBEjYuETglI5PsRHcCeC5pJhcrh7e7KzT6WmWyQzLjDNDFVyG4jDIgmeMH+dJ+217uadMMimuUUnu/+7Bv3WmKFXgNYo5wojP+5XmwZ614+6+UsAYzZDm5WAWC5w9ie83L7XSBaugsH1zL1ljiTMTFM9pxeoa3tPXTqe1HO4Bh51RC7vMIEpi1nG+JdW5JZts0GD/g7cS5nN64Cn/7kP6bKTzuXbgziJBsoEkbNskHeZhKbOzaSNTbUz6aOSwESYT+vb9CHDeXTNmmzWcfYLyfbzHqfzd/IDzthSNQ62GgaxXx/e6KlB+bGo9FxgiSvzaQMiy6BN1VhNV3MX62a0rZX0NqUaSMcUJq0byCOGYe+IEvdEsGFsf3o7Ge++pAVpjlulhr1lVwOXK2LS0bwDwbD9LIb5GgADmXyIGd7u87tOsduxE4KoLlecRfJnH0FfVUXnhU64gDUTvpjxW9oRq5lUnw==
  template:
    metadata:
      name: acp-signing
      namespace: quantum-platform
    type: Opaque
