apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quantum-platform

resources:
  - namespace.yaml
  - configmap.yaml
  - quantum-platform-secrets-sealed.yaml
  - quantum-platform-jupyterhub-sealed.yaml
  - quantum-platform-slurm-gateway-sealed.yaml
  - postgres.yaml
  - migrate-job.yaml
  - blog.yaml
  - users.yaml
  - user-api.yaml
  - ingress.yaml
  - postgres-exporter.yaml
  - admin-ingress.yaml

components:
  - ../../components/quantum-platform-agent-admin

images:
  - name: quantum-platform-blog
    newName: ghcr.io/nyameko/quantum-platform-blog
    newTag: dev

  - name: quantum-platform-users
    newName: ghcr.io/nyameko/quantum-platform-users
    digest: sha256:1cf5ad60de28410c296f72a56a95eb5d502ba83805848ffbc59c8a7cb10b8f38

  - name: quantum-platform-user-api
    newName: ghcr.io/nyameko/quantum-platform-user-api
    digest: sha256:59cc226a311bf6e6c14b08406d3e888283e5ff65253ab7db1345bf6cb4c81f85
