---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: quantum-platform-jupyterhub
  namespace: quantum-platform
spec:
  encryptedData:
    JUPYTERHUB_API_TOKEN: AgBnHs7Sz2sO+QqLFkV4YE5QayIwuKqTOUzeWjflsKocXnuWoOtJKT3AL+dhNjMpPgcgx3TGWtI56FHAueS0ks2DWVVD+r65NJ0KQykLjQUfUca+mJ8KQkOf2askNdv9QKi9Drzxq3RxJi3hMNEYWuBERcCm1bkmGO3GkM1qM8ohxuSNCe0vmQyQZlJbMjCgFWcIddJdlPMEotZ9Yrxm/L7l2/m32JOpOIvJHK91xHh/CwFwCMLboAhJKwyYSsyRsb20dLIDSe8bcZHR2JGxPyfEj9SKBehTdDgvGGgWIwy//LId7tc8G6Us5shez70RW5JMiq74iUkEzTZrangGCtNAcwQQZF+d0Ny9TkdRFA5tiOvHPjt4AdQleR2EfdQlgg9BW7qCYGKbSY/3rR33o8H5fR7Q/87VijKxXGEJPzT/Ky7RwDiAsnvlDtjJlrKSX+i3mYLqBNEO79F2qytehTgBk5HpuXf8kvn4npn6+49Kpf9jEc9ngbBpPEZy+GFHWQS0bcRNsvf+isHSHaLuuy7vbLYSAdydqGvIQtrGfuRhxuSRKFizG/IJvNHJi2rQOkBD7ViT5/VtpgVNNnZTv+GekzY0BHd9eXo9PvTs4Jhv68i10dLstVX0j0aYt/Q4ZzbhDyTGiYsi9k/R9ZUuucBbK9sUCWjTnwHxBLDPWA4T1eheCa1SP8ZijRcYTPYMFWzEOEeoobcaUFMoBweU/6f1q8LS3O4OdbFjXRNBolNYMNLi/rGzVg/4wZMaj7vZs9s8AqhNpwPZvNKSt2R7bVFN
    JUPYTERHUB_LAUNCH_SIGNING_KEY: AgCf432ajFN614j42j/MlsCAkc7s56GYDnEIvtAbSorKfgCxHoZ0AOZNGkQoS4BJwPS8a2t4yAilVkCodZWJM1G5D1Th8fyPgxxiHh5QfqVYl0nAzYr/m6CjKzW578zopP1/BuX3n9E596cSSJwjAn5hwttAanmsPM28XuHFuQmhuT0656xt94PgqDx2ML6FsAHgl1k6OdYKW2hOtVYacpPZn2/dp81dwSnsH13h4NXW6Hn+1bvJbxEa/Whs7OYx/oRp+4QE58K4MD5iFh9cFbA3WQP8i4zp0TgWkbCPLfhJBDuGRs+I4Oet/r5tTdB9/Dhhtb7Sa0HjT9w1eW9imm+uRV0OvMCI69ataPUI80f27TDMwaMKPb4SlSGDN9Z0JhJWRBwWlO8du2bJGKQ+5ES9rUtruVA2rCqH/ElDmXomn9tJzUbk5pl9tDVLNp+ZqCHsUAD9XM8IT7k3TSaJjquU2h/UP54og+P4XDoSImpoeIdK5e0pCZYxzTOin35F0/xzKLS7I7xeff7mCSjFCZufb9xVsR61FLdgjoYUAUX6Ck/fpYWowS6XZPa0EgIxuJgYUMSRDZxB1UHWrv0Pxr4dghn1lPGvjSvRTqgbQORKClHcg97lezRisDg7EXgcD5mAg/C9W6qRcp9vA1fuPNtjM5lYcPzlDbgF9hC7haFB1xaOy88CczJO2o+yuoZLN6bWIuUOZbzaXKgn1p57p6wmr7igW5G/QHzm99/7stt89rqaFn5MYusHExZZYlhiKBY+G++EiRMa6rwkoweiWDRD
  template:
    metadata:
      name: quantum-platform-jupyterhub
      namespace: quantum-platform
    type: Opaque
