---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: indexer-cred
  namespace: wazuh
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: AgCQcNHa4zAF02mC0vsOf9HKPET3s+cl3ZICGwkXZqMj8FyOSnOleQTHQkEbXDWjwZhZO0lsFLbwSGz2P7VMQL6/e6PqdoG1vQZhtPOAg6VIJ8joaxIHVSjMXHxmyKXsrSu4QU0NuVP8/bX0wQFlmPnXbaV9yGvOixVgay49V2kgOhIHTaCRD/gg/9B/u4KymQ2WPpCJqEK1d7qowWgydz8XtQDSpchaSapJmTfDkU+q7OeEbV9IlX1ShSDyyoLkcQKl/KEUe8tNvO99SUeP70Dm+nex7UfMPKyd3DdvKkVNoGm3LT1u+yjZkSiD8snL6hZMMY03WrvzhNdRfYPeE9HllGBnSm7L3c1/sd598R54o8Rq++v1cbxxlA1uVHmgd+ZnLZJFQuqHYZSffKLO0vvUJUeo4aTpp/WUNa6Tz+dgHg19FB5nqHWCMZzlqr/DbpHwcwCd9AMlpYmCB06bGozv08G8qhck0vNNcKwdjflzQq5M9c/Y7jwptXuNKZTvhvlGTqNuo1l/0zmua9AR/xy+ZtIANxSWsS/WjMsuj2N5373+4EHHvwsltsxygXzBIBeydZ6lJMa9cF9dpqNaEFhOK+1lQd0IKrrrbTUTSKFUiIhcF2ozVmg8iZFvBiz172Z9lUf/yXLa2Id5zGnrZqFGw+H3ZmFv2TMvve2hEXAHJZdoLU2MdeEOyLq8iBXrLrYpS5LPlFIl4YkJ+g/1kiM9YcruwS2mA35fTzv3lS0qVmMsoHFBiUtiqw4+KHF1JqQ=
    username: AgAo4dsrwYRrESR+S89XKmilJJoUuvxVZsEpnYI6ef4UdsTXzMgq9TWn9nDlO4FB+3kaoxAUFABYju42W8+kBOFjwSjmzMA2irWNgRql8Dx5TmUdHnVU/fNGdxKdLKSxCJnvxB6ai5aifWVVr2n2KubHeMyRQydYrnMs55UX5BCBDE+ZGVv9JD5guJcdy1/5C18bATgRYKfnFciGXBlLB275A43DufkeRiRs97EjEPPy4Hw9Vn5FCZYBaxy3ecbKBxxdNQZt6JDQDKPH+kc9zSSO8lkGR7pt+iExKwPBx/SxnBqwPgOIZbQyDUTxkSEDnm2GHtCBnohwOdv3J6xXFi/yNXMM3XPtQ03H0MDR+GqLjrtwk0m29DPLcHTiF5si31m14RCI+/V++FB+NWFZNvuqwavL19Bddrn3GtCNHfdygWNJwtUkamZi7U9hdDBUk8jbTsdiDXq7Z71Itm65TnrmTXL1Ok4eQ91hyc2lwHqzptzXX6MLZUvlI2L/o2qukUsTBGFv08LUpumQjoR1OVuii6VQB5SSVF8S69ah0tQajrmtrJ3pvQ1panK9/zT2nT/G5dOQ1YpaQz9ywGsbqnR35x9ISbTnGNjQkjMUNxcdz0uexh2MucCAWiCeOgE142ZFfPlF8ke1wyBA5xT5WUcDAgwF2ev1GXCydGdGYeKkK7nA0TV8BmrSkw+a7fM+xI0329QOiw==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      name: indexer-cred
      namespace: wazuh
    type: Opaque
