---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: indexer-security
  namespace: wazuh
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    internal_users.yml: AgAz1ja4Qj2ihfzCIYq4bl9vnzze1wvDIksNijaAsmaFjhiLub9BIXyZxSfDZEP2gmBwCrob4buMWtZhEvhV5fah3c9lY1mC8b9xoHbrrHFgvTHc+2Vf9Xj2RsYvFe8kbLMm8C0jvIklDroLHU8MOyRPCrfN0GcJmrtQAZEO3QYdoYVV0rjSpVtlJQiHq+xykmI7fXyPqTMjQUPNgv+nH2kQpYR7vLvw+M70IG3CIAT0JJ4+g1ZQ+bQ4nzoMSNmplEVBY8P5Ply4rrnEsPnu+kcc7H7s5ygS+0y2Ucc34IXnKsm0UmntrBLM26mGQGmSM3lka54NIgnewu1XYh3bQMwyglyhVnhN3MbkfvXwTHuzMsAXIIe1xfaCZ26qIleW5B9foEy5Disajf5P5CVaZ8bIj70LZ0eai7p7SrbHxVuOstYe9dgKC/CAPQUW443LrWM0v76uuC1mYVdeu+bs8JdbZIJyARpIsiAHRtMNM6PdvzWDfYoEDp3XtWpej34OgvtsUpmR1tTSswX/vqP1AB7psUN92V5d3imt8FgtWN7dk9LiAeADQyE97Vm1eJdUhiXyDDJrtz8dgVAXFr8A6frFwgQVaj9TzIHw9h0aBJFZDd6U7xFwaXOSDMSq4DvoPkh/c2Siaf/eONHCTTyK/xMUOuzQDB7Tw0Wx0E+W1f6FNwq2tQptg5KUKBN9OoMY3Guj22q6uoW0rJeRLk38e4kwtwLLbi0MnOe6qd1dka5KU+GnuL6lPR3I2JKGVZ59BgVTjv3yEisSzk0FWCrTgq7lDZ0sK7Sx4j9LYv3FJYibeUnvcHlyuNyGhwNZVGzMR7MplFKXYVgWlfons/pbAb0qta7pCOZ6i0RAQd5bR77jE2HoYwmb/OXj57mIDDsLnwU1OWIOY8XuNTcAOU0g740R25hs/hIMAzJfMogyDcvE/iI3AjUi2ODJLac9iFEj75Y/t2C1ryclnfTLfaVVI226WLeFs8+N+IGRiU+AE/j78mf4cqKRJnWm/Huomg/zW9cUxGSAd55R1qqLN1YmZroWVnHLdGU+TaJUG3w9fXkCB2DCPBE8DDuCGeidr6eaHkuv5FP89ilWpujgAEPs3xCW0/KMjaJxCK8dFTNitPfkZkok4DGtNj9X/gh9qcfEy4Z/VyDl+TOs44BiLlWXLtCsELlCpJ/NTTY7xlyq0EgOg1UWMdm95Rw=
  template:
    metadata:
      name: indexer-security
      namespace: wazuh
    type: Opaque
