apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: indexer-cred
  namespace: wazuh
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

spec:
  encryptedData:
    username: AgALGIkRZL+IjzvyhZp8WNLnE3vOeM/fCnwLftieH44cIPEyY36Nv67BJAY3AEz4rapEcLA0gWvvS9LLovCj3jL9fWKZL1bkDv4lUdtastvHJx4GzTzMOzJZmdEMyf7G57nO1MfcRZxnQpI03AY9Ez1cEI7v0UY3ReHMFe79ixetD4fSGDrYk1Hpw+83rP0Vcl+4/tj2kXLGQlVlx+tN58BFw+I6u30PJp6u8fcG9Q6YNsqYO7OgRBqfkGZOKrYiI7OvqFKkbwcrm7zGlFXqnbxRZ5KIxykpx7czGUvyfo5oiDSM4ZoxZIDLEr8WTZafI7LnouDZNm5U6u/bckBkBdiumyViq+nU8nDUKsxN755sSsHxM8y7wezf90845NcByohHSnvLPiFjmIC9XzE6wrB7vyprutKEPtsNtYJJOnI2NW15tM7r6rK1PrKMQFI0BzXWMcEwrNKtJ61vcWYE1ZixGmii0EIYe00IjnKHdYuVuzfmN+0Qd5FFYNWAfP5bhENMCG8fZyLjyjjYGaPTB9sRfdcIZJqT2hk4+kHphMlQHunr1guMauM+HJ4llcr68EJbtwMRNBsdv3tsFrYxw/em/Rmnn/5tO5/woSFnmK96lcaUQK+n8CZxz/MApZRxHxDKKqiZaWoU4WehEpFuc0wleBtcW4lGDDs6kW/Vimaofwanc3ZAyESF+5zu570x68L9a+3Wvg==%
    password: AgA8AkBUIk/lhgL4jk2gt+JNOIi7Hs2fK6FMI5aTzpvpkfaPquLKHoacWUXnd/f2hBgyr7SDZnvLUqwwtnTWKr1i1z4/kvv1UuS5Db24PXE5pnJ5G6KynxCbuRFP3LXZc2AD9CE5r70hexQvna65aKY4WBrnvLkoKeLzlxm2+XuSBBXdx6HpDcpkttFrqv3L8uEIRDi+moEcbKCRblt6PfqGsMGAZWeyp/oc2EAxalfCuUv8mDCwYe4vpLNWErLP/uCOjHdI/81B7eDh4ghKrYBdH4KnWWtrkDAOUqbBeXJXKqBELf5GjJkQwNT2JNf1X3vq9ynK8ZnEgyjF+eEeTfesjFp4JPzUO2cDsHcl6kbX/+rovcXDSC3u1nMe1In+sv/Dm0dEt9PAjo+54scJ8bbSez2MKPR9rUCp5Yk+fF/rYLLTeoJsrpGAX4EFWE2QcpOsHVMp/khya5nihwUUlLtVQHVe9jU3l8Oe31NUaFnKPLySn/uoe6xVJr53ccvSl3oIf64xlew9q8LJmnM6jjoLUH+vRDNo776vSQofBUi9qo+HQR3ort+T+NpwkBDkl5FbjQIMwP68mHSeScfwCmbNeoOpbK7OFKvGQjfPnvZyY6gLN4EZmmur0DuHJKG78DkFQbmxJoAWFlu8fCQeOzLKUhFXR/2abYpaHegKxBsZbfHWC9qIm+E8qWvplkwIPbL8uhKxmZfkSGstSLmZVewULo41O71j3/SGr6sxd/4CNaPEjjXFAYpcfs1s5AwS8rk=%

  template:
    metadata:
      name: indexer-cred
      namespace: wazuh
    type: Opaque
