apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wazuh

resources:
  - namespace.yaml

  - indexer-certs-sealed.yaml
  - indexer-security-sealed.yaml
  - indexer-cred-sealed.yaml

  - indexer-config.yaml
  - indexer-services.yaml
  - indexer-statefulset.yaml
  - indexer-ingressroute-tcp.yaml
