---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-api-cred
  namespace: wazuh
  annotations:
  argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: AgB46RXRM0qB30ycvy/ZW0/cDijfIdPKWySeBomwZtieVFVsGY0ZNguRXFbiQmscd2bRJHlJcWSouiE1r6p2ConsRF8W5XjbTuO2dqzqcQ/cG/xyQnu4lZ9mmmXXWLz5g4DcVXfMUaGhVGNiwxpVH46lp7QX4xY+UXbzhzdbBZzmbfpPWuJF3dW76tEeSOLyZIphtMJ8aEkpJrbLQ4d7O8x65o8862wqh48shV/AikTaa++gqczkad+1kRSasVixjCHiq29KTp4vZQ8ahMUVjSyAnvODjXKbn0qUZpt/bSAkfg1+2cspgXW4/mJL19FeykdKLra0Rk1ClPUOlTM76w9xlbUiSmlulCbHOb2euOGTfH4VbxyUGcVa79XCxiaW2OlONN1QxSXZ3/+uTUta0xxgAcGfVhL09Nb4ucaAdJxuU9EkhdwjtcWrz8GTUp09Sp6CI4I/jmZ2fjDOqrtEZweGFTPtqG/rb775MQy671jr75vir2UGAmCjD9cs18JEPlJ+fgG7CDGKtiKW2TV8YnI+Z+UVSmsPMvEIawmf1IIkd/VD90qwgc3EVBV3dbjZf45ng/bDoeClIM5DbhgBxmwnEK0HI2kJl5WMWZ9gC1Vt3RYJI4yvxa8W3SuoDPaZ3UVsHzsMW41eLYLa+PPsYAqQUPZcf6inyx2YGz6YXrFB6D1boyZPdo7bguEbHIERm3yWSVr3TzA78UOQCpitVziufWsz0BJ3ZqtER4SAuf2A7rr2BJCFoWJ35UZt7w==
    username: AgAMzurOQd5GGmGUpsbgJa4R2+9R/JcnbtEZ9NJoVNfCQQQeqfx2Z87orOcy49/f7rmNw+EXFJv5zUfvmrBRaekwcSnz0pD5hd7Ugz8AGEK+QDVhZHUgJ5TylrI5TqNigUP/123n6WT2XUs7NhIK8LP2wBBfg+DM9R37ivnmKeUoEPvVbZDbSasynLDtDQZGB2448nVgP9T/M/LWDnDCDA83dYMzVSNW88DxawD+Xpe6p/NZaIZfiTv8LUXifs5Zm78Mj/4fA4B2GhMPhm8jaDVupUEfJ5iuUoxpaw4PwNGMfgmk9YFzdXuzw41KdNQ3pFwvKabyY7hPqmaSwnAua7ziH4em9qtXIcAT6ZwxNNEclJFl7V74UdN2SmHC5nKvBOQGwg81tSXA8sYvVRD+Y2Mc3VnfrQMlQ/bPq+lQlm9ewEYit9TS1dc6NYi38oNCkbBymIsy8qQfM9enAOjn92im5CtGbezeC0prAkslonMHP5cdvFruytbcyr04e5x1y5kNxPKyg5IsNw4nq3lZBGDojYPJiqvch43w4brvtNzQq28TJ/NKuwb8Pny+m052iYjLuD8pkBwlVbVEY8cG6mDwzR3aYdaTcFO3TvyUQ3WEKXZd5njtb+DxXexA9cO3kA8uSGKXuivTJ4PpO9ilFzNUXg9ELdMPzp2zzBghIY3hwY2YlBTSBD/zY0eA4Gecq+UGcccLYbO5CMw=
  template:
    metadata:
      name: wazuh-api-cred
      namespace: wazuh
    type: Opaque
