---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBpSUR5e647BLr8LYMvZFktCytdGvWkE8Ult/GP/dbyDGSk8Od6cX+c+DUdnebnCmKgnsOW4c7aj6hC+8TRCGWd9jui5wShLDUmZ3XWAe7PP6Zw3KvPdpr4bn588xLAMhqr9/wM/TQqKRK8DsdmSsqLxtEQUsZsuGIBN5NEW70l5+2BCKhaspkaXPnO3Yu0MlVJEVrteZGJeCKX11vXMfrwg37JNWXAhMpG3wZ4JgPy6HO4pQWzI4Z1NoSoufSFCdkCVQxq+Syik/eZoxuUP08kxw+7ah8w793unHBGePwaA5K1Z4Ctou750CIsbMoGlxdeEHX1Nhl23+IdV8SE4scGgTxfGx4y0GHrAp+KSLO8ND3gHjvBb9HNHYzLWQyKGG6Y8lygfZJCHrtIlyAAUf9uZ79/4m4waBw7NaZLZ1VgKnWeSzySRslWiRuNiy4Lc0jgK3dYsMeLtfiG1FcA25wKWRHLzbi4EAQD6HFGvUhGn05Bs0oT/yk5daTWHOxqL90TE+JEPDzhvnSjj1bA13Y6vFtflpzuUXLaVX0hd6pjuLp4Y9wmd212soFlS8J0Jx1id3phZIBD2SB6o1+q2Lx4Q+j9B8NBPo2OBnPks2WKiqOvm3FQlkDjLJl2OYuqVjghP41vL00V9r9O5pRLeiNQSguWmhCcMpMGcoB0m5ltS5AhoQj8XV0YYGWQc7RO7iWqk4b73SIy85NbM7OjU3zeHf7Iy02sbSc=
    admin-user: AgB0XuFytEEtUvfvfYxpp+LgLpbvJscIQcGLexKXstjLFtSjsk9BDdcC5FXKw3HkZmFmbzpe58n2aEg6FM3uhH1jp9H2KyY47yT6Q82qP+5o9BDlSRn8QuvZJOefAZ8oh745kgZYRDJeGA4aaomq4IovBKoFBpYMhgNEzusup73ZXTerk5fvw+8sKg4Z2Dzj2S5w5e+QMqGAhZTnbof3coe64hdZoEv9u2fKicTUlKCgZLhKdmdmOn9gtKPrHXBBRjhfcs3InUnCXxISUWfkoAx5ZP2dmR7bMADt/s7/zsrJofsrRjDyZgBWsAneykDrb8CpwOFaHlCuGbolClz4qJbAHIkI9+8w3TKWE8sN77+mBTCFt79Ce/naMPr+RsSIo0AXC2p1lLribpbaBvOZW1DCRfkSSJhmpJIE6Nbpmf0eLzspuJQaVC0WpMe4ExNO4CPbBOe1v07/+dbGVwUZ2OWkGU9pB7C3Asi1A1dr0sCvU46VceAkzmf3r9KK9cvbGQujowGNZxCQ0kEua4Lvmi1sx/bzUUJjNXVCf3R89BFSsWgUY4pMYq54ZPA0BHV3h6RlbcDB8wVqzL6eGdBdt92GbR4rnL+KaTCS/ogGcA539RsvxcJRW3JlYESJQv0Gu7C7NM2wWO1YHFU+DeNfQZmat6LDEJA0+hk1Z0kIEDF96OyqB/rEhm5z6Vu1eMAY5ORiJt0a8A==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
