timezone: Africa/Johannesburg
kubernetes_minor: "1.36"
kubernetes_exact_version: "REPLACE_WITH_EXACT_1.36.x"
containerd_version: "REPLACE_OR_LEAVE_REPO_DEFAULT"
api_lb_type: haproxy

kubernetes_api_endpoint:
  address: 10.51.0.100
  port: 6443

kubernetes_api_backends:
  - address: 10.51.0.11
    port: 6443
  - address: 10.51.0.12
    port: 6443
  - address: 10.51.0.13
    port: 6443
#kube_api_endpoint: "10.51.0.100:6443"
kube_pod_cidr: "10.244.0.0/16"
kube_service_cidr: "10.96.0.0/12"

slurm_cluster_name: "qc_simulator"
slurm_control_host: "10.50.0.12"
slurm_partition_name: "cpu"
slurm_compute_nodes:
  - name: slurm-cpu-01
    addr: 10.50.0.30
    cpus: 12
  - name: slurm-cpu-02
    addr: 10.50.0.31
    cpus: 12
