apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jupyterhub

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: jupyterhub-control
    newName: ghcr.io/nyameko/infra-hpc-qc-k8s-jupyterhub-workbench
    newTag: dev
