apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyterhub-workbench-hub
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jupyterhub-workbench-spawner
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "events", "services"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jupyterhub-workbench-spawner
subjects:
  - kind: ServiceAccount
    name: jupyterhub-workbench-hub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jupyterhub-workbench-spawner
