apiVersion: v1
kind: Service
metadata:
  name: jupyterhub
spec:
  selector:
    app: jupyterhub
  ports:
    - {name: proxy, port: 8000, targetPort: proxy}
    - {name: hub, port: 8081, targetPort: hub}
