---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: acp-model
  namespace: agent-control-plane
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  encryptedData:
    ACP_MODEL_API_KEY: AgCW9rdvoU8960AuKBoMySzovJ0w8I7+rP4LEYEf4y0KuggL6sgGExb88svBN9bkzxKdGexQmnDqkgcxGzDbmgeVIirE8P0UUm8HQHtmN2Mhi5h9YC5ibQLVyFLWPAri20kj2432yS81BedmM+j+ILeKsDgUhD4Vke3Ed1bEJuRqMOPeCfgOM9nNBtCFIVSHktdIuYHPgL14RjFpfpKQzOAdy3d0PZ+L45jQ1Vepoqm93DPR7gFJFCfE6Nr8HLKPazeDP4wToaalWaYSPbRg/FKrMTb1/bAbHJsnuvegStzDSlQiyJpenq0UX/vxlRwSPiaPekguDkiEiM9K4fyYDadM0YUMFCrdBbEc1mfYfMOJOGkogB1++ZvxckUCwM3L4nODUIkB0PCZ5nTxA/ZSmxVTLnQq8QJsTbc9NRfa2KggcceXVh+NCl+Gm1wgqW8+t1RuQwbL8xVa3t2RS02ovmg9yBu8JArxj715RgBc3+hrpHWKbKp5u0TScZw6hH1ko4kCshm7Fe06JZre+z9qsSJj755KU3u+V2Mmk6ptb+zA8mRoSpO0G5d45kWIbG1RqC/jPH8t1JOHPeJMLyJlunMCteQ0QSpXdJN5KDdEmUJgoUJ2XdfMjaE4JfSih6m1oTqq4CD8E1N+Z21e1teCnzF9S/8js7HY7xGy8TsXXUMSJplD5vdDIH6YspUtuRvckyIx3VuDGgUdwuvGJ66KdAklwhvt2eg=
  template:
    metadata:
      name: acp-model
      namespace: agent-control-plane
    type: Opaque
