---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: acp-db-app
  namespace: agent-control-plane
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  encryptedData:
    ACP_APP_PASSWORD: AgA9g38A+5OCxToEbD5Jq1og+kMX4hXbneSSRtDPB5Y3x3NaatprwSfZqlcY+yZIYjzE8sf7QHWFuM786QF/yIT+vgX6PA6BNas63XX8PJQ8jfqRUf9Vp3g0JXu1q7I3nWbFb6bWBQJWKrWSeptYC9SN4P4ozrfiWW/l49mPjZc+VQaT6OL7O2J/X6ZtOc5euZLmtHLrhUz0zPT/FohmYvFgZr1CaJ26/4feaczioe6P14zoxwudeo638LyH12TfTtHrD64a8SfY8d9eiHCs7HoXF3/q/WR1uY0i0yvb9qXL9gBrRFEobJ9VSmlHUfLjYNVMqueDDAnBLPjepY+2yHvddyL8WwzZnr3Im1dy7hjPrTQDZ4mjwwaMYDZRMwKIsXEOA8aL+FCqC4+2WmdaQwjPWyh3Echx/t1vM6dnap4NRxPgKMPnoBEQ0JnQVeU7qvWnZgzOEaEBRfqBJp+xN3NWTcUJxbzeGo1Mjl/zb8rjdudsUQ31tWn+NVERiK7Iu8FUyMJj71asIKorddigzXWhvrUOW2RypIDkh9wg10VWwbb0LKYxaoB98SJUaEfig/Yxzv1YB1OrQEqmfkAnIHpre22m0SMCd5NESN+KJeg83TKd3SbeAthmwhDEPe/0ouHJI+VNHqfOJGm+oLuuwZdoizrT0Wz1VKyZneV4ZadFEHeos9SdntWLVl6b86qyygrcn9ClcptDt9F+DrWIVbzms6M9At+8OMIf0jokcIkFjXKQGirdYGtIbErVhrL3V80=
    ACP_DATABASE_URL: AgC0RYNCoQ1EVA8iOAMf1hiz0rftypNuPW/EXKNoNr3uxlVMcWYav8BibiKlTgY99ObPwuMrbY4rVrdC8V/0Ya3rvuEFU7yK3J/77XMUt3AiE/xgLLo4uL2S4ejrPUhqlh9vPe9maV8Wq9oJ1qg7hmEiDtpDVBufKnruDBMgZnZ7VF0rqpNff+hdpKJpZzlNPa92+h4JmWs6CVv8J/uSShUA9hd95M6UBMRru+pbP/qu3VlWVMt8li5lXFNa5l51OSENor/7m28OzNTNc9BqMp1/CLf6x3yLIrxndKmAR6rdvJ+0Py1DD2RTWoefTdmaMEfFpAPO2WV3UWqvTQ772/nWaYN9N7wtg0q7CAimPmRlB6NIuuYnK9esZx5EBb1ypoTkyWrKytdUCGqNpgsIMi8ktXY8l9ohk44MQCozfQI3e+oGwRwurEXfLqfUYHfEjD8hfDzLmNr5uNtqCRgqCjh+LR4Rrp8LLp+jBoQPx9b6DOGtgBfJVDYyuz7TOZ4Uo9Y9tvsmrvkiUkOQqOILhwkSWNIirR2PEeOcoEDw/4TYs7zXQ5bXziHeHHTUB1F1p9aWr+RF8ygLIAbnyhrIzJwl2D6D2alIZ/qbPWuQRs9SKnshjQm1CAAtPHuFaZnb5uu7R115iYq254DR0uBjBaqZG9xjAkJGYzHfVJNPQL5K9IVRuBUEczItPAbdNM/dj+o5JqGxCa7/Weux5wrrf+7lSMtwYbs23MdWUex3221tfcav1Ai1h2zkqlycIg94vjcSYBTGqbrj78UfvPrfmed7Sd2odIQSztzLfO4wRsJxd3YB2WgbcFqPK8zBL2gxs5CKYZwV5wsg6VCb0Oq2SBzWOtCmp2NRSKzT10SulVouag/2usaNXLV8nW3dCTmy7t17FTq3oYV5EyxzjaX6r4aJNQ==
  template:
    metadata:
      name: acp-db-app
      namespace: agent-control-plane
    type: Opaque
