apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cinder-agent-retain
  annotations:
    argocd.argoproj.io/sync-wave: '-4'
provisioner: cinder.csi.openstack.org
parameters:
  type: SSD
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
