all:
  vars:
    ansible_user: ansible
  children:
    edge:
      hosts:
        edge:
          ansible_host: 10.50.0.10
    hermes_orchestrator:
      hosts:
        hermes-orchestrator-01:
          ansible_host: 10.50.0.11
    slurm_controller:
      hosts:
        slurm-controller-01:
          ansible_host: 10.50.0.12
    slurm_login:
      hosts:
        login1:
          ansible_host: 10.50.0.20
        login2:
          ansible_host: 10.50.0.21
    slurm_compute:
      hosts:
        slurm-cpu-01:
          ansible_host: 10.50.0.30
        slurm-cpu-02:
          ansible_host: 10.50.0.31
    api_lb:
      hosts:
        api-lb-01:
    control_plane:
      hosts:
        k8s-cp-01:
          ansible_host: 10.51.0.11
        k8s-cp-02:
          ansible_host: 10.51.0.12
        k8s-cp-03:
          ansible_host: 10.51.0.13
    workers:
      hosts:
        k8s-worker-01:
          ansible_host: 10.51.0.21
        k8s-worker-02:
          ansible_host: 10.51.0.22
        k8s-worker-03:
          ansible_host: 10.51.0.23
