---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cinder-csi-cloud-config
  namespace: kube-system
spec:
  encryptedData:
    clouds.yaml: AgBuVqUKyqmj/C4ksHrax5q0rXRzAvYv/oylimU4Y4Am5MwZBT5JZMydeu1xBuBlbkmmDrKNTNKLyNyOTlbngRw2KBN5vXfyFLz5fGHPwLeKW07uMm8LoweFI3hZaSaYUrgLunZtc1jCgnahdQoT6MwO1G4q8MQ27hAfr4a7w8J6fPZoze5yNlytTBzw7EyeINMoIW8woOTo4nu3qolQbJq0ilfdzjkJWhqRN/Tli5jt4TMxW4NvpZxxPJh9SkXv06HjWomkFP6v/da6gNsLmjMHm+3+ZaKxEXxTXKl0dJCsH6dg8NV3Wc1na7rVqHaO4rhoPvLYF7aLglcxA9uIr3L51Iq0F4Tx4tgawfHB3/gZmpMv81PO6fV5xBOf/4JPzUFdsJXmbeFzgHvgVUXqreZp4Dp9dNMQ+iWO82+jSbJbanHPRIq90gCQ0EcYXDxS+vrvJHaYLHUGhJQd7Qc4iZT2fFqyy370k8UwkDXVvT9QsncOGRZN93qrfcj//IZQDYNuG+5AQYe0b1L9TL9iuV63dF+003ssGA3e2G183lpZ+m2UZt/HnatGKA4haDIzx4Ss7SpPF6crzXc0D5S4DxVyLY9hDySViwZKHXK9lmmQ59iDG/pdA+i3An6Px47KRCZSDH7Ns51gM61vvJtooJABGCYe3TaL5sydSM8EkDK/B95T/S/MtwnnUXoyCtU4ATdJBx6Wzl9gAeWMAn6wJz9302hQ4UEyRpkNyO5MtlVHP/2HhSTfCvodrhf2GAkXB1Z5SVqdcI/X/rWJWcxc2YuKWei+S71dHjMMXtO2opMsQ+f7S6jySNSHPQToIXF+IcnfT6OGgxmlivko3D5kjpcGVZ4sC9mu3SoWjtcnzDulbQxT3oEPscGnK2nJVJ8TgyDzaq0QQczt0+bI8EOhLRueJxiDe7dkHmlir9JI201QKVplbM/xKcr8iB4yu7SeNzb5Yr2ULNRI13rLlIBp9NkJboUxF7EzPDQAYlUG9HDvN4CoSO1E89G2zwg8U1fW1iXeD2TKiQr3diKl09Tmg+3KBVnwUkBibXOLTMO14LlV5qtpmi2GrBn6uBSiOqrxfcm3zV0xz8hhcWQWStxaG5LVzqCCbVLboMnh5daek6ye5RkYJfsRwAhzvhajY2Mzzn0+7sG6cPr5jXW4jkLg794WfitMU0ZGPjOQb94oZ9CKOCIBuVpBiejwDnbQ/iuUnJRjfH/knERwml+yDUQo+uziNDiJTXKJHlBjZ6GGK55sb1PcL2JCTJL3gui6xedLCqvWCwpfn2QDvBKC5ra3Ew/cKwB2GuY=
  template:
    metadata:
      name: cinder-csi-cloud-config
      namespace: kube-system
    type: Opaque
