---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cinder-csi-cloud-config
  namespace: kube-system
spec:
  encryptedData:
    cloud.conf: AgCev6ZlhBWl4/r3ub0dsuh9/kvPnuU+e3KkX4PoTkb2YFm3O0izEr+paayMtsL7aNnxCAd+k3TW24u7BnyhZczRqUfNmvGLCI50p8ftFzjGDDLIZ2abMd5538dChX8HmHtOegcw8ToCJIy1YKFe7n8D4t2EjNVKEQfCHw1cFPf+XUISztQNJ4BS44rL4qUdz4AEibeBheWk3XKNuNvyrl20kSYFUxplZJZKd0pvwkZjnzTd3XiweveSRJ2Ek5Mqe5WpbcES04FyM3NQmOj0a0HWNv+zXpuNdw1iMa7rPXwy6h2cSCB+7QjYl/1jwpubrMNBRMGBaGBpqWe9O+aUnF7Z7JgZX5dZeAgpgRl8VG+dqM8iAeJTz3tWspFnXJv0swiSbxR91xIce3FUUTr/wkASzIq+CvHyq9ke7lzvs/vhr3zh3+9ETPH5cAMiwJ72IclBlMCQYLl2NmmgsXMErG61eGsvdD5vIv8Z0BSobRY20PhkRtBI1n8tSKHeLtQwvZ6ek4VXbYDdesYz2bZibEfTJe3F+k77FpvPczM4Q/PyEkWTlyeiQv0L+q6PW0JohduOXd2LjbZW08NDCqpnCYPHT6SS5uFjHt51Hq6wwZms5nE4LgtHlV8OdvN+1//4QuEseXvQ5C03IcB2a8tNHBPr46mwz2H9Ak8/pDTVz+IAgmQ8jKptfhSYvzp3buA3VmRKIQPVkZEwfSgo71i/fRhGMBUpDK9VYsq5BD/1+Z8H5VfqywUiGnomtZyCB9ULZv3ddcINGTE/nsqgBv4Q8k5R8IEC6aHwS1SAp8OE2gh/f2rQ3Uc3H9t9tlB/jytzBS+Nn5DcN4cCZYbr7FIUt3iQTTfW3upULNEeXuiyeZjQhbBQYvWqNjhicn7S/56n3w8J+yBZZaDMSETIpRgfBJjmoTFBaEhA7s6039gO8fbwAAOSlTD02oPmgpP2sO9M3gV/ut8Feb0FgrrSmWwysI/82yHKefWHxTirOn8Mwm7VAj7EH4J6psMxZCQVpSREgVabmySrvHaqtmLAB6Lv9DFJ/japhqBMl3M6/MnCGmE9RkyTpsxcx4RKUhkXnDH6Dwl1iqg32DKLKe3VemkbvRgqZH1hayJ4w3NqahnGuUwNddiZhenX+oP7QJID
  template:
    metadata:
      name: cinder-csi-cloud-config
      namespace: kube-system
    type: Opaque
