---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cinder-csi-cloud-config
  namespace: kube-system
spec:
  encryptedData:
    cloud.conf: AgC1yNAMBBzH0O5cGa7yeY/T97Ci2SyHgZtf28KQr+YGl25Qp3MzFmu5SBbd5vP8sAMqLx6xlVCcLR6hWVku40PTn4iSuUXXQNlN9zBzc1AMQRCVRwVtmj6Q/ScED0qF4J3KwoylDZOloeNkKCXOpm1wLeMArwrX0VtdoCWrAVkjKFIp7OQWEjoTnHyt854RHLbPg/i4u0Ke05QeJrKBxcwHmifbfEmh7mHxGbXRYtCnlewfM2YsGfqbrnoYQY+/WtcmcBo2aX9dA5REwhDtz3bHgVPzMfTF0nuGA5wNmqU/jer0HYY4ippcVv2wZPuIesHNl0+WxhSs0YlPnuhxQ07cF5pSIQdK1FW2jeso97mV2+vu46kONy997X/rD8cVHZWmWKaMZUrFAyt2OsVz//7JGMGKmaDVOmc1YEvrkRgV+krdTdKtR/wJl5+9DzFvEOh/EVEyIGl4bHa8h8bbmWBAbNPxCjgSznUgbg5DdTXTRPKsyGx5R/gW/n4o/ZfM2Vd+LwGCQHyoM7fa+e7k6lE4UoS8yX72VGvuZ6UzZyKWd4g7dKMvrwtol4i/lmoC9DGbyM+pUKo2VSPviyQLN44Bi1CR3KGOKgkK4FTNQMyytv7f0owMZkXSOSxzw4kwdgaSjS1xTgaqEbbUHxKHcApy2LRR0AwB7cG+bEyQ/+wfBxpl6kBtOCAHUKaE3ETw27zcC93QD+NZ4UKxHbiLncBuojJOJRP9YnkI/uZqloyiz2da92WBS8ZRzp6YGbwz2FzkJ56QnUljLABWtdVkg0awgjO8RUgy5P0LRHktWQ4LNpFP5UUgNPDdwygJfUalAuFBT3VcwrN2LGxqW4BzCmOc4uD5himYKWMkndj1sEIVDsyZ2fxm8/YtsHq8CmNLSET0U55ZPEdiTQF/QVta7pnUC2/uV3kYacNHUhOuHdxDKq2CwOIgl3X+77hRQF9n2QpVnqLq5bSkjrNe1BPmabHJ1jYJ1NiBGkUFljqC6LBceLBnqUyk0ijs4skce/54Lyzs8+eDriYYxrKU9JgE0JVbjOpSvU6+qqssvYBlv/ZFzEqg3DMqubRvlztRPcHM3vUJIhu7YvqI1b8e94coX1JYjvQhYAlHsTkp4+O6iO6RDPbVjWfzkgJPCrQ7
  template:
    metadata:
      name: cinder-csi-cloud-config
      namespace: kube-system
    type: Opaque
