apiVersion: ENC[AES256_GCM,data:hS0=,iv:99yJCRWXC+y86VhtBnsfFkyFET/PjxWLU7WmZb7h12w=,tag:fX5ASEQWhVfyqYZ8Xd1zJQ==,type:str]
kind: ENC[AES256_GCM,data:YaNhQeXh,iv:5UyZl8KBWF7k3tl9/vSY8zDR7cw2GGsUM9ufgoKQsKs=,tag:0QQHj1UYJwUu9qP6rNreyA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:24I1bh4Fo9RFPP1/RbtCikiTuWmGlLA=,iv:RZ89wyRpdtFtAPZTKt+RLmWiikSB4h6pJ0uipiYZhkg=,tag:vtZU5uN+H4Lh3b6yJeY9WQ==,type:str]
    namespace: ENC[AES256_GCM,data:2fa0lwHQiQx8IWs=,iv:3MkTFaZ+iRzkaSD/59mmNlfbV8KJj6S1AhtW3tIzBbY=,tag:NmBwtQvilG0ISPCP5lmRng==,type:str]
type: ENC[AES256_GCM,data:4C+WQHSZ,iv:jsOidY1eyZVSp7QjV1u7zWN8c3Vc90hBhJiFP5WE2Os=,tag:sxvoScWD1l1At5sKs2NdKQ==,type:str]
stringData:
    cloud.conf: ENC[AES256_GCM,data:70OC4uY/TgL+OMXiw3a5bsOThAMdSckhCKI32zn9mZDUpMfuqZskyKUrrDxS7kRa95aZGrUd6xv57UurgVvUeALorS2ZRgz9I+ywCmP389hnz6R9ppV3Y8qowuFRyDHjUViS0BdvQnHYHb1rdA7UtDgE/m50qsZ8B5IQzrrgYjSkhhO/6HNj4NpqBJH91PgL1DRMvjOU+HXwRlx3i4G+0LRnKVygjlPj6dA8A5FKIEZjpxKBBt0tFYvdwiqvEJy/HfQjnhbVcZ8sIZK5LkK7Qgy5LY7KLZRLGCjedA2Mqw0kQUnWPdP8rfA3RZK75S3tNxpbBtVvlvGe7Rx79udr2F/YmMUtpFfqFbl9/oASQiQuG5kP3nBukdI4FtALlKvldBC9TYRy2nJ2TsQTkulaOBcmo/E=,iv:TLwRFoMfX6XmjmzORli2IB41XykYUSL3A5n02JRT1B4=,tag:y+o3wgVMzYMOgdiIAvZ7LA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bndBRXRVSTBxNkc2dUFy
            UENZQkp1SkF2bTJZcjkvUmo3NlVRY2VlZ2prClZCSEVMV1dmRGo1TEZDaHdEMVBO
            UUllbHc4elFKU1dKRVJ2WjFRYUNjTVEKLS0tIElneFpSQmNxQm9YV0d5Q2hrNWJW
            eGVDUk55RFNmMHViZTJqUE45VEJhbEkK0/QyX7VvcdSfuhYUSFcFK3l85tFmah6H
            dCWSe1lk/Hwevk44g6dX+rixLG5LL449ADIu3Kgx/0AQfMcDnklkPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15h0ptktk0ny783jvutztsa00kglxryfa6usl62r2kxt4jru49ugqympj87
    lastmodified: "2026-09-05T12:57:54Z"
    mac: ENC[AES256_GCM,data:OHau8LlGzV6Axww4sAinzB9+Dfj6cfBCibC0+DWo3hfpOC04RxmGvve8J3WDKrH+ug43uddQUIo46G1P85d9/vEcbY6mwLoQYzBYUAfRkkPMv4a/v5AuMVUo7/hl9O9/qafPihtWocqJz8L+mHEBkuhUapVuYGPoniq3l3yFpPs=,iv:1tgUFGiAQwbcYNqYZApa7WbKL4SkcJ2TmHJhWwsahf8=,tag:NfvzcDVfNhV7B5YDg+ZFrw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
