---
- name: Import Wazuh GPG key
  ansible.builtin.rpm_key:
    key: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    state: present

- name: Configure Wazuh repository
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/wazuh.repo
    owner: root
    group: root
    mode: "0644"
    content: |
      [wazuh]
      gpgcheck=1
      gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
      enabled=1
      name=EL-$releasever - Wazuh
      baseurl=https://packages.wazuh.com/{{ wazuh_base }}/yum/
      priority=1

- name: Install Wazuh agent
  ansible.builtin.dnf:
    name: "wazuh-agent-{{ wazuh_version }}-1"
    state: present
    update_cache: true
  environment:
    WAZUH_MANAGER: "{{ wazuh_manager_address }}"

- name: Enable Wazuh agent
  ansible.builtin.systemd:
    name: wazuh-agent
    enabled: "{{ wazuh_agent_enabled }}"
    state: "{{ 'started' if wazuh_agent_enabled else 'stopped' }}"
