image:
  tag: v3.7.13

deployment:
  replicas: 2

providers:
  kubernetesCRD:
    enabled: true

  kubernetesIngress:
    enabled: true

ingressClass:
  enabled: true
  isDefaultClass: true

ports:
  web:
    port: 8000
    exposedPort: 80
    nodePort: 31818

  websecure:
    port: 8443
    exposedPort: 443
    nodePort: 31924
    http:
      tls:
        enabled: true

service:
  enabled: true
  type: LoadBalancer

log:
  level: INFO

accessLog:
  enabled: true

metrics:
  prometheus:
    enabled: true
