image:
  tag: v3.7.13

deployment:
  replicas: 2

providers:
  kubernetesCRD:
    enabled: true

  kubernetesIngress:
    enabled: true

ingressClass:
  enabled: true
  isDefaultClass: true

ports:
  web:
    port: 80

  websecure:
    http:
      tls:
        enabled: true

service:
  enabled: true
  type: LoadBalancer

logs:
    level: INFO

accessLog:
  enabled: true

metrics:
  prometheus:
    enabled: true
