---
- name: Configure edge admin
  hosts: edge_nodes
  become: true
  roles:
    - edge
    - wazuh_manager
    - role: wazuh_filebeat
      tags:
        - wazuh_filebeat
    - wireguard
    - role: pihole
      tags:
        - pihole
    - role: suricata
      tags:
        - suricata
