---
- name: Initialize Kubernetes control plane
  hosts: k8s-cp-01
  become: true
  roles:
    - kube_control_plane

- name: Join additional control planes
  hosts: k8s-cp-02:k8s-cp-03
  become: true
  serial: 1
  vars:
    kubeadm_control_plane_join_command: "{{ hostvars['k8s-cp-01']['kubeadm_control_plane_join_command'] }}"
  roles:
    - kube_control_plane_join

- name: Join Kubernetes workers
  hosts: workers
  become: true
  serial: 1
  vars:
    kubeadm_worker_join_command: "{{ hostvars['k8s-cp-01']['kubeadm_worker_join_command'] }}"
  roles:
    - kube_worker_join
