apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jupyterhub
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - jupyter.quantum.nyameko.com
        - jupyterhub-hub.quantum.nyameko.com
      secretName: jupyterhub-tls
  rules:
    - host: jupyter.quantum.nyameko.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: {name: jupyterhub, port: {name: proxy}}
    - host: jupyterhub-hub.quantum.nyameko.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: {name: jupyterhub, port: {name: hub}}
