- name: Write SSD persistence marker
  kubernetes.core.k8s_exec:
    kubeconfig: "{{ cinder_csi_kubeconfig }}"
    namespace: "{{ cinder_csi_validation_namespace }}"
    pod: "{{ cinder_csi_validation_pod }}"
    command:
      - sh
      - -c
      - 'printf "cinder-ssd-persistent\n" > /data/ssd/proof.txt'

- name: Write HDD persistence marker
  kubernetes.core.k8s_exec:
    kubeconfig: "{{ cinder_csi_kubeconfig }}"
    namespace: "{{ cinder_csi_validation_namespace }}"
    pod: "{{ cinder_csi_validation_pod }}"
    command:
      - sh
      - -c
      - 'printf "cinder-hdd-persistent\n" > /data/hdd/proof.txt'

- name: Write DEFAULT persistence marker
  kubernetes.core.k8s_exec:
    kubeconfig: "{{ cinder_csi_kubeconfig }}"
    namespace: "{{ cinder_csi_validation_namespace }}"
    pod: "{{ cinder_csi_validation_pod }}"
    command:
      - sh
      - -c
      - 'printf "cinder-default-persistent\n" > /data/default/proof.txt'
