apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterhub-workbench
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nyameko/infra-hpc-qc-k8s.git
    targetRevision: dev
    path: argocd/resources/jupyterhub-workbench
  destination:
    server: https://kubernetes.default.svc
    namespace: jupyterhub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
