apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/nyameko/infra-hpc-qc-k8s.git
    targetRevision: main
    path: argocd/resources/traefik-test

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
