apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: <PINNED_VERSION>
      helm:
        releaseName: traefik
        valueFiles:
          - $values/argocd/resources/traefik/values.yaml

    - repoURL: https://github.com/nyameko/infra-hpc-qc-k8s.git
      targetRevision: main
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
