- name: Install Sealed Secrets controller
  ansible.builtin.command:
    cmd: >-
      kubectl
      --kubeconfig {{ admin_kubeconfig }}
      apply
      -f https://github.com/bitnami/sealed-secrets/releases/download/v0.39.1/controller.yaml
  register: sealed_secrets_install
  changed_when: "'configured' in sealed_secrets_install.stdout
                 or 'created' in sealed_secrets_install.stdout"

- name: Wait for Sealed Secrets controller
  ansible.builtin.command:
    cmd: >-
      kubectl
      --kubeconfig {{ admin_kubeconfig }}
      -n kube-system
      rollout status deployment/sealed-secrets-controller
      --timeout=5m
  changed_when: false

- name: Verify Sealed Secrets controller
  ansible.builtin.command:
    cmd: >-
      kubectl
      --kubeconfig {{ admin_kubeconfig }}
      -n kube-system
      get deployment sealed-secrets-controller
  changed_when: false
