---
- name: Install edge packages
  ansible.builtin.dnf:
    name:
      - nftables
      - wireguard-tools
      - bind-utils
      - podman
    state: present

- name: Enable nftables
  ansible.builtin.systemd:
    name: nftables
    enabled: true
    state: started
