---
- name: Import Wazuh GPG key
  ansible.builtin.rpm_key:
    key: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    state: present

- name: Configure Wazuh repository
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/wazuh.repo
    owner: root
    group: root
    mode: "0644"
    content: |
      [wazuh]
      gpgcheck=1
      gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
      enabled=1
      name=EL-$releasever - Wazuh
      baseurl=https://packages.wazuh.com/{{ wazuh_version }}/yum/
      priority=1

- name: Install Wazuh manager
  ansible.builtin.dnf:
    name: wazuh-manager
    state: present
    update_cache: true

- name: Enable Wazuh manager
  ansible.builtin.systemd:
    name: wazuh-manager
    enabled: true
    state: started
