---
- name: Check Slurm client can contact the scheduler
  ansible.builtin.command: sinfo --noheader
  changed_when: false
  register: slurm_login_sinfo
  retries: 6
  delay: 5
  until: slurm_login_sinfo.rc == 0
