apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cinder-ssd
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: cinder.csi.openstack.org
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  type: SSD
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cinder-hdd
provisioner: cinder.csi.openstack.org
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  type: HDD
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cinder-default
provisioner: cinder.csi.openstack.org
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
