---
- name: Install Kubernetes repository
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    mode: '0644'
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_minor }}/rpm/
      enabled=1
      gpgcheck=1
      gpgkey=https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_minor }}/rpm/repodata/repomd.xml.key
      exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni

- name: Install kubelet, kubeadm and kubectl
  ansible.builtin.dnf:
    name:
      - kubelet
      - kubeadm
      - kubectl
    disable_excludes: kubernetes
    state: present

- name: Enable kubelet
  ansible.builtin.systemd:
    name: kubelet
    enabled: true
