rbac:
  create: true

serviceAccounts:
  server:
    create: true

alertmanager:
  enabled: true

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true

prometheus-pushgateway:
  enabled: false

server:
  enabled: true

  replicaCount: 1

  retention: 15d

  persistentVolume:
    enabled: true
    storageClass: cinder-ssd
    size: 20Gi
    accessModes:
      - ReadWriteOnce

  service:
    type: ClusterIP

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 2Gi

  global:
    scrape_interval: 30s
    evaluation_interval: 30s

extraScrapeConfigs: |
  - job_name: haproxy
    static_configs:
      - targets:
          - 10.51.0.100:8404

  - job_name: quantum-platform-postgres
    static_configs:
      - targets:
          - quantum-platform-postgres-exporter.quantum-platform.svc.cluster.local:9187

  - job_name: quantum-platform-user-api
    metrics_path: /metrics
    static_configs:
      - targets:
          - quantum-platform-user-api.quantum-platform.svc.cluster.local:8000

  - job_name: slurm-hosts
    static_configs:
      - targets:
          - 10.50.0.12:9100
        labels:
          slurm_role: controller
      - targets:
          - 10.50.0.20:9100
          - 10.50.0.21:9100
        labels:
          slurm_role: login
      - targets:
          - 10.50.0.30:9100
          - 10.50.0.31:9100
          - 10.50.0.32:9100
          - 10.50.0.33:9100
        labels:
          slurm_role: compute

  - job_name: storage-hosts
    static_configs:
      - targets:
          - 10.50.0.40:9100
        labels:
          storage_role: nfs
